name: WhosThere
main: com.sleaker.WhosThere.WhosThere
author: Sleaker
version: 1.1
commands:
    who:
        aliases: [ list, players, online, playerlist]
        description: lists online players