name: WhosThere
main: com.sleaker.WhosThere.WhosThere
author: Sleaker
version: 1.4.4-b000
depend: [Vault]
commands:
    who:
        aliases: [ list, players, online, playerlist]
        description: lists online players
    whois:
        aliases: [ seen ]
        description: get detailed information about a user.
    testcolor:
        description: test color parsing