name: WhosThere
main: com.sleaker.WhosThere.WhosThere
author: Sleaker
version: 1.2-b000
depend: [Vault]
commands:
    who:
        aliases: [ list, players, online, playerlist]
        description: lists online players
    whois:
        description: get detailed information about a user.