name: WhosThere
main: com.sleaker.WhosThere.WhosThere
author: Sleaker
version: 1.4.6-b000
depend: [ Vault ]
commands:
    who:
        aliases: [ list, players, online, playerlist]
        description: lists online players
    whois:
        aliases: [ seen, lastlogin, lastlog ]
        description: get detailed information about a user.
permissions:
  whosthere.whois:
    default: op
    description: Allows a player to get information on when a player was last online.
  whosthere.admin:
    default: op
    description: Displays IP address and other information about a player when using whois
  whosthere.who:
    default: true
    description: Allows a player to get a list of all online players
  whosthere.staff:
    default: op
    description: Anyone with this permission will show up in the staff list